spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grain
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.atguigu.grain.user.bean